### ISSUE TITLE
count files

### ISSUE THREAD

**Issue by abearab** [josephreplogle/CRISPRi-dual-sgRNA-screens#2]
Hi @josephreplogle, 
Can you clarify what is the difference between the two different outputs of the `fastq_to_counts`? 
- `{sample_id}.AB.match.counts.txt`
- `{sample_id}.all.aligned.counts.txt`
Thanks

**Comment by jreplogle** [comment]
{sample_id}.AB.match.counts.txt contains only combinations of sgRNA A and sgRNA B that are known pairs in the input library files (excluding results of lentiviral recombination). 

{sample_id}.all.aligned.counts.txt contains all combinations of sgRNA A and sgRNA B found in the sequencing data -  including combinations that are not found in the library file (and likely the result of lentiviral recombination).
