### ISSUE TITLE
dual indexes libraries and SampleName issue

### ISSUE THREAD

**Issue by dumplinggy** [josephreplogle/CRISPRi-dual-sgRNA-screens#3]
Hi @josephreplogle ,

Could you specify does the "SampleName1" indicate the gene expression library name, and "SampleName2" indicate the corresponding CRISPR feature barcode library name? Also, could we also use this pipeline for dual-indexes libraries (10x genomics CG000316 RevD)? 

Thank you very much.

**Comment by josephreplogle** [comment]
To clarify, these scripts are for aligning CRISPR genetic screens (with genomic DNA readout), not scRNA-seq genetic screens.
